### ISSUE TITLE
swap publish time and log time in message record?

### ISSUE THREAD

**Issue by wkalt** [foxglove/mcap#105]
We currently have publish time physically ordered before log time in the message record. This isn't a big deal but introduces a couple inconveniences:
* The description of the publish time references the log time, which a spec reader will not have read about yet
* The log time is the time on which the file is most closely ordered (under most conditions) and the one on which the indexes are built, so it may be more natural somehow for it to come first. Since all the fields are fixed-width, the difference is just cosmetic.

The corrective action would be to swap the ordering in the record.

**Comment by defunctzombie** [comment]
Done in https://github.com/foxglove/mcap/pull/143
