### ISSUE TITLE
Request from Homebrew maintainers

### ISSUE THREAD

**Issue by p-linnane** [foxglove/mcap#1063]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. I'm reaching out regarding the automated version bump PR's for mcap. As part of our merge process, we push our built bottles to the PR branch. Since your automated PR's are being opened from an org fork, we are unable to push to it. This requires us to recreate a new PR to get the bottles merged. I'd like to request that you open future automated PR's from a non-org fork to simplify the merge process for us. Thanks!

**Comment by amacneil** [comment]
Hey, thanks for flatting. I think https://github.com/foxglove/mcap/pull/1064 will fix this.

I also submitted a readme update https://github.com/mislav/bump-homebrew-formula-action/pull/150 to `mislav/bump-homebrew-formula-action` which will hopefully reduce the number of others who fall into the same trap.

**Comment by amacneil** [comment]
We won't know for sure if this worked until we do a new release, but I can keep an eye on it.

**Comment by p-linnane** [comment]
mcap has been added to our autobump list, which means we automatically check for new releases every few hours and automatically open a PR if one is found. You shouldn't need to worry about opening PR's.

**Comment by jtbandes** [comment]
Is there any way the maintainers of this project can be notified if a future bump fails to build? Will the homebrew maintainers open an issue here?

**Comment by p-linnane** [comment]
We will try to fix the build, and if we can't then we would open an issue here.
