### ISSUE TITLE
Potential malicious mcap library on PyPI

### ISSUE THREAD

**Issue by howard-mahe** [foxglove/mcap#1070]
**Description**
Hello, all of the releases of the `mcap` package on PyPI e.g. [mcap 1.1.1](https://pypi.org/project/mcap/1.1.1/#files) are blocked by the navigator. If I download any of the release by working around the navigator, none of the hashes (sha256, md5) for the downloaded files match the ones provided by PyPI.

- Version: Any releases of the `mcap` package on PyPI
- Platform: Any

**Steps To Reproduce**

Download `mcap-1.1.1.tar.gz` on PyPI / Download files.

**Expected Behavior**
I expect the hashes of the downloaded files to match the ones provided by PyPI.

**Comment by indirectlylit** [comment]
Hi @howard-mahe, thank you for the report.

We did briefly reproduce the behavior you described, but now do not see it anymore. Would you mind trying again, and posting the hashes you see if it's still an issue?

The SHA256 hashes we are seeing are:

* mcap-1.1.1.tar.gz
   `699cde9f98350bece709a416591a2acb4ce5c0d8b07773b846f6b416bd993efa`
* mcap-1.1.1-py3-none-any.whl
   `d494988b76124b01de42089a02183b598f80e9bae3d44f5d30dd469752fa8b58`
