### ISSUE TITLE
python add message fail:struct.error: argument out of range

### ISSUE THREAD

**Issue by Xen0sWang** [foxglove/mcap#1137]
**Multi thread writing message fail**

traceback:
[event_urecord-1] Traceback (most recent call last):
[event_urecord-1]   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
[event_urecord-1]     self.run()
[event_urecord-1]   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
[event_urecord-1]     self._target(*self._args, **self._kwargs)
[event_urecord-1]   File "/opt/udeer/nodes/urecord/event_urecord/lib/python3.8/site-packages/event_urecord/event_urecord.py", line 374, in encode_processing
[event_urecord-1]     success = self.encode(target)
[event_urecord-1]   File "/opt/udeer/nodes/urecord/event_urecord/lib/python3.8/site-packages/event_urecord/event_urecord.py", line 423, in encode
[event_urecord-1]     self.image_detect_wrapper(event_info)
[event_urecord-1]   File "/opt/udeer/nodes/urecord/event_urecord/lib/python3.8/site-packages/event_urecord/event_urecord.py", line 49, in wrapper
[event_urecord-1]     data = func(*args, **kwargs)
[event_urecord-1]   File "/opt/udeer/nodes/urecord/event_urecord/lib/python3.8/site-packages/event_urecord/event_urecord.py", line 718, in image_detect_wrapper
[event_urecord-1]     self.image_detect(mcaps, os.path.join(self._paths['output_path'], event_info['name']), ["udeer.drivers.Image"], topic_name_filter=[
[event_urecord-1]   File "/opt/udeer/nodes/urecord/event_urecord/lib/python3.8/site-packages/event_urecord/event_urecord.py", line 466, in image_detect
[event_urecord-1]     writer.write(
[event_urecord-1]   File "/opt/udeer/nodes/urecord/event_urecord/lib/python3.8/site-packages/event_urecord/utils/mcap_util.py", line 125, in write
[event_urecord-1]     self._writer.add_message(
[event_urecord-1]   File "/usr/local/lib/python3.8/dist-packages/mcap/writer.py", line 196, in add_message
[event_urecord-1]     self.__chunk_builder.add_message(message)
[event_urecord-1]   File "/usr/local/lib/python3.8/dist-packages/mcap/_chunk_builder.py", line 45, in add_message
[event_urecord-1]     message.write(self.record_writer)
[event_urecord-1]   File "/usr/local/lib/python3.8/dist-packages/mcap/records.py", line 315, in write
[event_urecord-1]     stream.finish_record()
[event_urecord-1]   File "/usr/local/lib/python3.8/dist-packages/mcap/data_stream.py", line 77, in finish_record
[event_urecord-1]     self._buffer.write(struct.pack("<Q", length))
[event_urecord-1] struct.error: argument out of range

**Comment by jtbandes** [comment]
Please follow the issue template when creating new issues:

```
**Description**

- Version:
- Platform:

**Steps To Reproduce**

<!--- Include the minimum possible code or example data to reproduce the problem. -->

**Expected Behavior**
```

In particular, this bug report doesn't contain any **steps to reproduce** the issue. Looking at a traceback alone is not usually enough to diagnose the issue. For more info see https://stackoverflow.com/help/minimal-reproducible-example

> **Multi thread writing message fail**

The mcap python library is not thread-safe. You need to synchronize access to the writer.

I'm going to close this issue for now, but if you'd like to add more details then we can reconsider.
