### ISSUE TITLE
python: Is there a way to append to write the mcap file?

### ISSUE THREAD

**Issue by asd12312394** [foxglove/mcap#1155]
### Discussed in https://github.com/foxglove/mcap/discussions/1154

<div type='discussions-op-text'>

<sup>Originally posted by **asd12312394** April  8, 2024</sup>
As title
 Is there a way to append to the mcap file? 
in Python mcap packages</div>

**Comment by jtbandes** [comment]
Closing this issue since the discussion is already open and we use issues for bugs.
