### ISSUE TITLE
rust: default next channel id is inconsistent with other languages

### ISSUE THREAD

**Issue by YXL76** [foxglove/mcap#1221]
**Description**

https://github.com/foxglove/mcap/blob/4fcdd339bf0c7b6297148f0d6a420a389fe8cf8b/rust/src/write.rs#L239

https://github.com/foxglove/mcap/blob/4fcdd339bf0c7b6297148f0d6a420a389fe8cf8b/cpp/mcap/include/mcap/writer.inl#L493-L496

https://github.com/foxglove/mcap/blob/4fcdd339bf0c7b6297148f0d6a420a389fe8cf8b/python/mcap/mcap/writer.py#L359

**Comment by defunctzombie** [comment]
Closing for no response. If there's more detail you can provide we are happy to revisit when you do.
