### ISSUE TITLE
Broken message if protobuf field greater than 14 bits

### ISSUE THREAD

**Issue by Oszimilian** [foxglove/mcap#1223]
Hello everyone,
I am completely new to mcap and protobuffers.
I have something strange in my program which serializes data using protobuffers and then writes it to the mcap file.
If a field in the protobuf message gets bigger (over 14 bits) then the serialized protobuffer also gets bigger (from 3 bytes to 4 bytes). This also works in my program. If I now write the protobuf to the mcap file and then read it out again (with foxglove-Studio or plotjuggler) I get an error. I then used an example from the repository to try to find out what is wrong here. 
Short example:
If I write this protobuf message into the Mcap file and read it out again, the buffers match and everything is fine.
Input: 08 a6 7c 10 a6 7c 18 a6 7c 20 a6 7c
Output: 08 a6 7c 10 a6 7c 18 a6 7c 20 a6 7c

If I read this one in, which contains signal fields over 14 bits, and then read it out again, I get a completely different protobuf. This is also not correct.
Input: 08 a4 80 01 10 a4 80 01 18 a4 80 01 20 a4 80 01
Output: c2 32 2e 3c d5 5e 00 00 c4 54 f6 4f 89 cc 95 c2

- Version: mcap/1.3.0  protobuf/3.21.12
- Platform: ubuntu 24.04

```
//Writing
void mcl::McapWriter::create_mcap_message(  mcap::Message &mcap_msg, 
                                            const std::string msg_str, 
                                            mcap::ChannelId channel_id) 
{
    mcap::Timestamp startTime = std::chrono::duration_cast<std::chrono::nanoseconds>(
                                std::chrono::system_clock::now().time_since_epoch())
                                .count();

    mcap_msg.channelId = channel_id;
    mcap_msg.sequence = 0;
    mcap_msg.publishTime = startTime;
    mcap_msg.logTime = startTime;
    mcap_msg.data = reinterpret_cast<const std::byte*>(msg_str.data());
    mcap_msg.dataSize = msg_str.size();
}


void mcl::McapWriter::write_msg(    const std::string &msg, 
                                    const std::string &msg_name) {


    auto it = _name_channel_map.find(msg_name);

    if(it == _name_channel_map.end()) {
        mcl::log_error( "Cant find channel id",
                        {{"Messagename", msg_name}});
        std::exit(EXIT_FAILURE);
    }

    

    mcap::ChannelId channel_id = it->second;

    mcap::Message mcap_msg;

    create_mcap_message(    mcap_msg,
                            msg,
                            channel_id);

    auto ret = _writer->write(mcap_msg);
    if(!ret.ok()) {
        mcl::log_error("Error while writing");
        _writer->terminate();
        std::exit(-1);
    }

}
```
Reading is with the dynamic-reader from the cpp examples (protobuf)

I would be pleased if someone could help me

**Comment by jtbandes** [comment]
Hi there,
This looks like an error in your C++ program. You should try compiling and running the program with [sanitizers](https://github.com/google/sanitizers/wiki) which can help detect errors like this.

Specifically, the `const std::string msg_str` parameter means the data will be copied into a local variable inside the function, so the `.data` field is left holding a [dangling pointer](https://stackoverflow.com/questions/17997228/what-is-a-dangling-pointer).
