### ISSUE TITLE
Rust version `0.10.0` not available on crates.io (wildcard ( `*` ) dependency constraints are not allowed)

### ISSUE THREAD

**Issue by HALtheWise** [foxglove/mcap#1260]
**Description**

This tag seems to exist in the repo for Rust release `v0.10.0`, but the corresponding release has not been pushed to crates.io
https://github.com/foxglove/mcap/releases/tag/releases%2Frust%2Fv0.10.0 

https://crates.io/crates/mcap/versions

I'm not sure who's responsible for this, maybe @james-rms

**Comment by jtbandes** [comment]
Thanks for reporting, we'll take a look.

It [looks like](https://github.com/foxglove/mcap/actions/runs/10870662481/job/30163547184) this is due to:

> wildcard (`*`) dependency constraints are not allowed on crates.io. Crate with this problem: `async-compression` See https://doc.rust-lang.org/cargo/faq.html#can-libraries-use--as-a-version-for-their-dependencies for more information
