### ISSUE TITLE
`mcap filter` with `-e`, `-s` not behaving correctly

### ISSUE THREAD

**Issue by mwcondino** [foxglove/mcap#1268]
- Version: `v0.0.49`
- Platform: Ubuntu 22 (in a docker container).

**Steps To Reproduce**
- Download the attached test bag `test.mcap` into local directory
- [test.tar.gz](https://github.com/user-attachments/files/17723600/test.tar.gz)
- Unzip - `tar -xzvf ./test.tar.gz`
- Run the following command:
```
mcap filter ./test.mcap -o ./test_out.mcap --start-secs 1727916694 --end-secs 1727916724
```

This fails with `configuration error: invalid time range query, end-time is before start-time` and exit code `1`.

**Expected Behavior**
No issue with this filter, as the given times are valid.

**Workaround**
It appears that using `-E` and `-S` works, but requires converting the time into nanoseconds. This is fine for my application. However, I was surprised that `-s` and `-e` stopped working; on my previous version (v0.0.42), there were no issues with these args.

**Comment by bennetthardwick** [comment]
Looks like it might have been a bad merge. I don't think this line should be there anymore: https://github.com/foxglove/mcap/blob/28627b721622183e59f7be8032cbf33033558a23/go/cli/mcap/cmd/filter.go#L80-L82

**Comment by mwcondino** [comment]
> Looks like it might have been a bad merge. I don't think this line should be there anymore:
> 
> https://github.com/foxglove/mcap/blob/28627b721622183e59f7be8032cbf33033558a23/go/cli/mcap/cmd/filter.go#L80-L82

Yeah I'm not familiar with the changes from the last release, but this blurb from the release notes stuck out to me:

> filter: Added --start and --end arguments that accept either nanosecond or RFC3339-formatted log times.

I just tested on `v0.0.48`; no issue with that release.

**Comment by stewpend0us** [comment]
I'm having this issue with v0.0.49 also.

**Comment by james-rms** [comment]
@stewpend0us v0.0.50 fixes this issue.

**Comment by mwcondino** [comment]
Thanks for the fix @james-rms!
