### ISSUE TITLE
CLI tool ros2 conversion reported nondeterministic failure to find schemas

### ISSUE THREAD

**Issue by wkalt** [foxglove/mcap#202]
In this issue: https://github.com/foxglove/mcap/issues/184

A user reports

```
The file size is a bit suspicious since it is a 1/10 of the db3 file. It also complains about not finding some schemas that are in the directory supplied. Running multiple times in a row the error of missing schemas changes until it fully disappears.
```
This raises a few questions to investigate:
* Is the size reduction real?
* Why is the error nondeterministic? Maybe iteration over the file tree is not.
* Why does the error go away? This seems like a clear bug.

**Comment by bertaveira** [comment]
I have been removing the file and trying it multiple times and every time I do it it is a different schema missing until sometimes it just works. There is no predefined order the errors appear or which messages it complains about.

Here is an example: 
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/9644729/153923205-b27dfb34-cad6-436b-9c2d-8a7925a6ecd6.png">

The messages in the info command seem to be right. In comparison this is the foxglove diagnostic of the original file:
![image](https://user-images.githubusercontent.com/9644729/153923329-6319d6ae-d650-41b7-ba87-10d76660cd7a.png)

The file size of the mcap is 197kb while the original db3 file is 1.02Gb.

**Comment by bertaveira** [comment]
Compiled the latest version and opened with the latest version of studio (v1.0) and got this error:

<img width="696" alt="image" src="https://user-images.githubusercontent.com/9644729/154166606-964967a4-95af-4cf3-8860-fd8b25bf4114.png">

If desired I can supply the converted file.

**Comment by jtbandes** [comment]
Thanks for reporting. Fixing that error in https://github.com/foxglove/mcap/pull/214

**Comment by wkalt** [comment]
@bertaveira I just merged a fix for another bug that could relate to your issue. Would you mind trying again, and if you still experience an error, would it be possible to provide,
1. The value of the $AMENT_PREFIX_PATH environment variable on the system you are running the command on.
2. Either the `tree` output for the directories you are providing the command, or (if you are willing) the tarred contents.

Appreciate the help debugging.

**Comment by bertaveira** [comment]
It does not give the error of the "schema not found" where I would have to run the convert command until it goes away. Now it converts every time. 

It is still just 140Kb instead of the 1.2Gb of the db3. When I open in foxglove studio I get this error:

<img width="698" alt="image" src="https://user-images.githubusercontent.com/9644729/154436037-1d8e3200-cdc4-47b8-9bf7-d2c54f45fba1.png">

If it helps I can provide the rosbag I am using for testing. It should not require any non common message.

For the info you asked:

1. echo $AMENT_PREFIX_PATH  give only /opt/ros/foxy
2. I can send you over slack the db3

**Comment by wkalt** [comment]
Thanks. Summarizing from Slack discussion:
* The nondeterministic failures bug is fixed
* The size is now correct
* I have opened a new issue, https://github.com/foxglove/mcap/issues/223, for the bug in the previous post.
