### ISSUE TITLE
Quickstart section

### ISSUE THREAD

**Issue by jdavidberger** [foxglove/mcap#227]
Coming from here: https://foxglove.dev/blog/introducing-the-mcap-file-format I was very interested in trying out mcap and seeing how it could fit in with our ROS usage. It'd be nice if there was a quickstart guide to just process a bag. I'd PR one but I don't think I know Go enough to do that justice. Here is the thing that got me started though:

```
#:~/source/oss$ git clone https://github.com/foxglove/mcap.git
#:~/source/oss$ cd mcap/go/cli
#:~/source/oss/mcap/go/cli/mcap$ go run . convert  test-input.bag test-output.mcap
```

Overall the file went from 17gb to 7.5gb which I found very encouraging overall

**Comment by amacneil** [comment]
Also we need to publish binary releases and add mcap homebrew

**Comment by jtbandes** [comment]
Closing this since some quickstart documentation was added to the website in #353. Feel free to reopen or file a new issue if you have other ideas for how to improve the docs!
