### ISSUE TITLE
Data discontinuities in data coming from data platform are not plotted correctly.

### ISSUE THREAD

**Issue by foxymiles** [foxglove/mcap#259]
**Description**
Data discontinuities should be skipped in plots but currently we connect them in data streamed from data platform.

- Version: 1.2.0
- Platform: All

**Steps To Reproduce**
1. Open a long file from data platform.
2. Plot some topic from the file.
3. Use the play bar to jump to different sections of the file.
4. Observe the plot try to connect the gaps.
<img width="790" alt="Screen Shot 2022-03-01 at 1 33 28 PM" src="https://user-images.githubusercontent.com/93935560/156245563-6c8daaf9-5cc0-461a-97b0-ca9da10c4490.png">

**Expected Behavior**
Gaps should be excluded from the plot.

**Actual Behavior**
Gaps are connected.

**Comment by wkalt** [comment]
@foxymiles is this an "mcap" issue or a studio one?

**Comment by jtbandes** [comment]
Studio

**Comment by foxymiles** [comment]
Closing in favor of https://github.com/foxglove/studio/issues/2956
