### ISSUE TITLE
String datatype is unclear

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/mcap#27]
**Description**
The spec says the following about string types:

```
String: a uint32-prefixed UTF8 string
```

Is the prefix the length of the string (characters) or the number of bytes for the entire UTF8 encoded portion?

**Comment by jhurliman** [comment]
It would also be nice to clarify that strings are not null terminated.

**Comment by defunctzombie** [comment]
@jhurliman see if the wording here is adequate: https://github.com/foxglove/mcap/tree/roman/spec-format/docs/specification#string
