### ISSUE TITLE
Open example.mcap in Foxglove studio

### ISSUE THREAD

**Issue by m3d** [foxglove/mcap#274]
I would like to experiment with MCAP format and see the results in Foxglove studio, but if I start with available example it shows that `text/plain` is not supported:
![foxglove-unsupported-text-plain](https://user-images.githubusercontent.com/5664353/157039502-6d625f96-a096-4232-ad2d-c95628df33c1.jpg)
What are currently supported examples? Thank you
p.s. I used `Foxglove Studio version 1.2.0`

**Comment by defunctzombie** [comment]
@m3d Are you referring to the example code on the python readme? Or some other example?

The example on the python README I've updated here: https://github.com/foxglove/mcap/pull/273

**Comment by m3d** [comment]
I am referring to code in README, yes - MCAP attached ... hmm could not be attached, oh github ... zipping ...
[example.zip](https://github.com/foxglove/mcap/files/8198626/example.zip)

**Comment by defunctzombie** [comment]
@m3d 👍 

@foxymiles How do we make a new release for pypi so folks will see an updated readme for files that they can open in Studio?

**Comment by m3d** [comment]
New example works fine, thanks :)
![foxglove-example-ok](https://user-images.githubusercontent.com/5664353/157061208-9a60553a-86b4-4d7d-bcfd-b44a882dbfeb.jpg)

**Comment by m3d** [comment]
p.s. you can close this ticket, thank you

**Comment by foxymiles** [comment]
> @m3d 👍
> 
> @foxymiles How do we make a new release for pypi so folks will see an updated readme for files that they can open in Studio?

We just need to bump the version in setup.cfg and tag a new release. I'll do that.
