### ISSUE TITLE
Make Chunk compression field a char[4]

### ISSUE THREAD

**Issue by jhurliman** [foxglove/mcap#32]
Right now, the `compression` field in `Chunk` is a variable-length string. This places the actual chunk payload at a variable offset, and requires parsing the `compression` string to determine the chunk payload length. If `compression` was instead a fixed-length `char[4]`, we would know the chunk payload size immediately after parsing the record length and it would avoid an additional allocation for the `std::string compression`.

uncompressed would be [0x00, 0x00, 0x00, 0x00] or little-endian uint32_t 0
lz4 would be [0x6C, 0x7A, 0x34, 0x00] or little-endian uint32_t 3439212
zstd would be [0x7A, 0x73, 0x74, 0x64] or little-endian uint32_t 1685353338

**Comment by defunctzombie** [comment]
After discussion we've decided to stick with string. We were not swayed enough yet that this is annoying enough to require a new type to reason about.
