### ISSUE TITLE
Do channel info records have to appear in chunks if they have appeared in earlier chunks?

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/mcap#34]
The spec says: `A channel info record must occur in the file prior to any message that references its Channel ID.`

If I write a chunk and know I've written a channel info record before in another chunk - do I need to write the channel info record again?

**Comment by jhurliman** [comment]
The diagram spells this out explicitly, showing an example of messages in a new chunk referencing the channel id of a channel info that appeared in a previous chunk. It would be nice if the writing spelled this out as well.
