### ISSUE TITLE
MessageIndex records type is incorrectly saying KeyValue

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/mcap#35]
![image](https://user-images.githubusercontent.com/84792/150583930-422246a1-be30-4f0c-a062-4ca1cd934e0f.png)

This is not a key/value but an array. Timestamps are allowed to repeat.

**Comment by jtbandes** [comment]
>This is not a key/value but an array. Timestamps are allowed to repeat.

KeyValues does allow duplicate keys. In a few places we explicitly disallow duplicate keys.
