### ISSUE TITLE
CLI: pack release binaries with upx

### ISSUE THREAD

**Issue by wkalt** [foxglove/mcap#352]
Compressing with upx seems to bring the binary size down from ~15MB to ~6MB.

**Comment by wkalt** [comment]
there may be drawbacks to consider here as well - online reading indicates this may cause false positives for antivirus programs and may also have performance implications (presumably startup time) on constrained devices.

**Comment by jhurliman** [comment]
I don't think 15MB -> 6MB is worth any extra startup time

**Comment by wkalt** [comment]
yeah, I agree - closing
