### ISSUE TITLE
Data recoverability example

### ISSUE THREAD

**Issue by jhurliman** [foxglove/mcap#385]
Given a truncated MCAP file (let’s say mid-chunk as if power was lost in between two block storage writes while flushing a chunk to disk), how can I see which chunks are intact and which are corrupted, and move the recoverable data to a new indexed MCAP file?

**Comment by jtbandes** [comment]
There's now a `mcap recover` command (#446, #599). Is that sufficient to close this issue?

**Comment by jhurliman** [comment]
Yep!
