### ISSUE TITLE
Chunk Index record doesn't tell me how big my chunk record is

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/mcap#39]
After reading a chunk index record, I know which message index record to read, but I don't know how big my chunk record is which means I have to go read the size of the record and then go read the record itself.

**Comment by jtbandes** [comment]
+1

**Comment by defunctzombie** [comment]
Change offset to start_offset and end_offset so we can identify the bytes in the file containing the `opcode+record lengh+record data` for a chunk index record.

**Comment by defunctzombie** [comment]
chunk_start_offset - points to an opcode
chunk_end_offset - one past the end of the chunk

[start_offset, end_offset)

**Comment by defunctzombie** [comment]
Add chunk_trailer_byte_length? chunk_trailer_end_offset?

**Comment by defunctzombie** [comment]
https://github.com/foxglove/mcap/tree/roman/spec-format/docs/specification#chunk-index-op0x05
