### ISSUE TITLE
Does data_section_crc include leading magic and header?

### ISSUE THREAD

**Issue by jtbandes** [foxglove/mcap#398]
Currently, the spec documents the high-level file structure as:

```
<Magic><Header><Data section>[<Summary section>][<Summary Offset section>]<Footer><Magic>
```

And the documentation for DataEnd.data_section_crc says:

> CRC32 of all bytes in the data section. A value of 0 indicates the CRC32 is not available.

Should the leading `<Magic><Header>` portion be included in the checksum?

As written, it seems like the answer is no, but none of our writers actually write a nonzero data_section_crc, and so the conformance tests aren't verifying it. A couple of writers have data section CRC implementations that **do** include the magic and header, but then just write out zero anyway (since the conformance tests currently expect it to be zero).

One could argue that checksumming the magic is unnecessary since it identifies the file format (and the summary section CRC in the footer does not include the footer magic). So perhaps the checksum should include the header, but not the magic.

Another point for discussion is how useful this CRC is at all. Chunked files can/should already include checksums at a per-chunk level, and attachments have their own CRCs — and it's unlikely that anyone would need double-coverage of the majority of their file with checksums (in a chunked file, the data section CRC would mostly provide checksumming for message index data). So it would probably only be used in unchunked files, likely on lightweight/embedded systems. Would such systems want to pay the performance cost of checksumming all their data?

**Comment by james-rms** [comment]
I think it's reasonable to give users the option of checksumming an un-chunked MCAP file. I also think there's no big difference in complexity when checksumming from beginning of file or from the beginning of the header record. If I had to choose, i'd lean towards covering the entire beginning of the file up to the DataEnd record.
