### ISSUE TITLE
Custom ROS 2 message definition files need a newline at the end for proper conversion

### ISSUE THREAD

**Issue by esthersweon** [foxglove/mcap#404]
**Description**
- Custom ROS 2 message definition files need a newline at the end for proper conversion

**Steps To Reproduce**

- Record ROS 2 file on Galactic, and then try converting to MCAP in Humble

**Expected Behavior**
- MCAP file is successfully created and deserialized in Studio

**Actual Behavior**
- Created MCAP file uses incorrect message definitions, and is not able to be deserialized in Studio

**Comment by wkalt** [comment]
closed in https://github.com/foxglove/mcap/pull/450
