### ISSUE TITLE
Why does Chunk Index have a crc field when Attachment Index does not?

### ISSUE THREAD

**Issue by jhurliman** [foxglove/mcap#43]
It seems like they should either both have it or neither have it. My personal leaning is toward only doing CRCs on user data (chunks, attachments) and not on index records.

**Comment by defunctzombie** [comment]
Why does Message Index have a crc?

**Comment by defunctzombie** [comment]
Remove crc from every record EXCEPT - Chunk and Attachment.

The reasoning is that if you want to crc your message data (and channel infos) use chunks. Attachments don't go in chunks so need their own crc.

**Comment by defunctzombie** [comment]
Keep it in the footer
