### ISSUE TITLE
MCAP equivalent of "rosbag play"

### ISSUE THREAD

**Issue by scottfharvey-cm** [foxglove/mcap#461]
Hi, we are evaluating whether to use MCAP. Is there an example or library that can do playback from an MCAP? Ideally would have similar features as rosbag play such as changing speed.

**Comment by jtbandes** [comment]
Hi, can you confirm which framework you're working with? Is this ROS 1 (and what distro)?

**Comment by scottfharvey-cm** [comment]
We're not using ROS. Ideally the playback is independent from the middleware (like ROS) and we can plug-in our own middleware from the example. Thanks.

**Comment by jtbandes** [comment]
In that case the best thing today would be to use one of the reader libraries depending on which language is best for your framework. For example, C++: https://mcap.dev/docs/cpp/r334C087DCDA491C1.html#DE0BCDAB8DCD9D31

**Comment by jtbandes** [comment]
For ROS 1, MCAP does not provide a huge benefit over rosbag for simple recording and playback workflows. For ROS 2, we offer https://github.com/ros-tooling/rosbag2_storage_mcap. For other frameworks, it’s a bit outside the scope of this project to provide a generic playback tool, because each framework will have its own specific playback needs, so we aim to provide comprehensive reading APIs that people can use to build their own tools.

If you run into any issues using these libraries, feel free to ask in GitHub Discussions or [Slack](https://foxglove.dev/slack)!

**Comment by defunctzombie** [comment]
@scottfharvey-cm To add - we are currently working on making more examples for reading and writing mcap files across different languages. We'll be adding these examples to `https://mcap.dev` to improve the experience for folks writing lower level framework tools like logging and playback. Until then we are happy to answer questions in discussion, email, or slack!

**Comment by chfritz** [comment]
I had the same need. It turns out that it's pretty easy to get it done via the mcap python bindings:

`play.py`:
```py
import sys
import time
import math

import rospy
from genpy.dynamic import generate_dynamic

from mcap.reader import make_reader
from mcap_ros1.decoder import Decoder

rospy.init_node('mcapPlayback', anonymous=True)

if len(sys.argv) > 2:
    speed = float(sys.argv[2])
else:
    speed = 1

publishers = {}
clock = -1;
def publish(topic, schema, message):
    global clock;

    # If we have not yet seen this topic before, generate message class on-the-fly
    # from the included schema.data and create a new publisher for the topic.
    if not topic in publishers:
        decoded = schema.data.decode()
        msgs = generate_dynamic(schema.name, decoded)
        pub = rospy.Publisher(topic, msgs[schema.name], queue_size=10)
        publishers[topic] = pub

    rosMessage = decoder.decode(schema, message)
    # wait until it is time to publish this message
    if clock > 0:
        time.sleep((message.publish_time - clock) / 1e9 / speed)
    clock = message.publish_time;

    print(time.ctime(clock / 1e9), end='\r')
    publishers[topic].publish(rosMessage)


decoder = Decoder()
with open(sys.argv[1], "rb") as f:
    reader = make_reader(f)
    for schema, channel, message in reader.iter_messages():
        if rospy.is_shutdown(): exit()
        if channel.message_encoding == 'ros1':
            publish(channel.topic, schema, message)
```
(License: Apache-2.0)

usage:
```
python play.py MCAP_FILE [SPEED=1]
```

The script ignores all non-ros1 messages in the file.

I'll try to publish this as a package on pip.
