### ISSUE TITLE
Audit and document quality/feature parity across each language

### ISSUE THREAD

**Issue by amacneil** [foxglove/mcap#490]
We should document level of support for each language:

- Document tier of support for each language
- Review supported features (e.g. indexed reads, ordered reads) and standardize these for Tier 1 supported languages

**Comment by jtbandes** [comment]
Note that there are multiple levels of ordered reading. I believe some readers support chunks being out of order, but don't make an effort to reorder/merge messages across chunks that overlap.

**Comment by defunctzombie** [comment]
Adrian: make a matrix of features

**Comment by james-rms** [comment]
Feature matrix here: https://www.notion.so/foxglovehq/Library-Feature-Matrix-43bc4544abf3463884fb719ec449b264

**Comment by amacneil** [comment]
👍 we should move this to public documentation once we have the website up
