### ISSUE TITLE
`mcap info` shows incorrect start/end timestamps for my file

### ISSUE THREAD

**Issue by jhurliman** [foxglove/mcap#501]
**Description**

When running `mcap info` on [whattimeisit.mcap.zip](https://github.com/foxglove/mcap/files/9238763/whattimeisit.mcap.zip), the following incorrect start/end/duration info is shown:

```
$ mcap info whattimeisit.mcap
library: python-mcap-ros1-support
profile: ros1
messages: 100
duration: -460947h7m35.322474798s
start: 2022-08-02T11:07:45.222474798+08:00 (1659409665.222474798)
end: 1970-01-01T08:00:09.9+08:00 (9.900000000)
compression:
	zstd: [1/1 chunks] (80.31%)
channels:
  	(1) /tf  100 msgs (0.00 Hz)   : tf2_msgs/TFMessage [ros1msg]
attachments: 0
```

Studio shows correct start/end timestamps for this file.

- Version: v0.0.13
- Platform: MacOS

**Comment by jtbandes** [comment]
The message start/end time in Statistics appear to be swapped from the chunk index:

<img width="493" alt="image" src="https://user-images.githubusercontent.com/14237/182454648-a75d27cb-6ccc-4546-b029-79c6eea842fe.png">

<img width="496" alt="image" src="https://user-images.githubusercontent.com/14237/182454530-d34a180b-b41a-48c7-8619-3f6061a4f583.png">

<img width="483" alt="image" src="https://user-images.githubusercontent.com/14237/182454463-ec29f8fa-e061-4e53-9213-fc880e7045bc.png">

**Comment by jtbandes** [comment]
I don't think this would be considered an issue with `mcap info`, unless we want to start adding error-detection features to it, but those belong in `mcap doctor`. I would consider it a bug that `mcap doctor` doesn't produce any errors when run on this file.

**Comment by jtbandes** [comment]
Studio and the Quick Look preview for whatever reason use the chunk start/end times instead of the one from Statistics:

https://github.com/foxglove/studio/blob/main/packages/studio-base/src/players/IterablePlayer/Mcap/McapIndexedIterableSource.ts#L37-L46

https://github.com/foxglove/studio/blob/main/desktop/quicklook/getIndexedMcapInfo.ts#L66-L77
