### ISSUE TITLE
`mcap sort` command to sort an mcap file

### ISSUE THREAD

**Issue by alkasm** [foxglove/mcap#525]
It might be nice to have a command to sort the messages inside a file (by log or publish time, or perhaps both). Apparently there is ongoing work to support reading messages in timestamp order even if the mcap was not written in order, as mentioned in https://mcap.dev/support-matrix.html. If go support is added soon-ish, then this command would be as simple as piping the mcap file to a writer with the order-preserving reader.

**Comment by jtbandes** [comment]
Related: https://github.com/foxglove/mcap/issues/446

**Comment by bryfox** [comment]
Completed by https://github.com/foxglove/mcap/pull/1009; v0.0.37
