### ISSUE TITLE
`mcap doctor` reports no errors for corrupt mcap file

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/mcap#535]
**Description**
> NOTE: I _believe_ this file is corrupt based on not being able to open it in studio with a bad magic error. I looked at the file in a hex viewer and the start of the file is ok - it is somewhere later in reading the file that Studio fails (possibly when it thinks there should be a footer record).

The file is our converted nuscenes.bag -> mcap located here: https://drive.google.com/drive/folders/10TFUJgvhOPqpSQ-q8tSbQum1CX33aO3L

When I run `mcap doctor` on this file there are no errors. But opening in Studio shows this error:

![image](https://user-images.githubusercontent.com/84792/185209953-7f675e06-0c1a-409c-89e0-d06232679896.png)

Studio uses the typescript reader so I imagine the result would be similar outside of studio for direct users of the typescript reader.

**Comment by jtbandes** [comment]
Note that the "bad magic" that studio complains about is located _near_ the end of the file. And it seems like the file does not end with the expected trailing magic.

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/14237/185224745-7d3ce17a-9884-4443-9c59-c549f232d8de.png">

**Comment by defunctzombie** [comment]
@jtbandes that byte string also occurs in many other places in the file (at least that is what I saw in my hex viewer).

**Comment by jtbandes** [comment]
Oh yeah, you're right it does. I was just looking near the end because I wanted to see the trailing magic.
