### ISSUE TITLE
`mcap convert` should support ROS 2 Eloquent bags

### ISSUE THREAD

**Issue by amacneil** [foxglove/mcap#567]
Here is a very simple bag file I created with ROS 2 Eloquent:

[rosbag2_2022_09_07-06_23_46_0.db3.zip](https://github.com/foxglove/mcap/files/9503297/rosbag2_2022_09_07-06_23_46_0.db3.zip)

I tried to convert it using `mcap convert`:

```sh
$ mcap version
v0.0.17
$ mcap convert rosbag2_2022_09_07-06_23_46_0.db3 out.mcap
failed to convert file: no such column: offered_qos_profiles
```

I believe this missing column is the only difference in Eloquent bags, so we should handle it gracefully.

Side note: It's weird that despite this error, `mcap convert` still generated a 176B `out.mcap` file. If there is a fatal error, I would not expect to create an output file.

**Comment by wkalt** [comment]
the content is an empty mcap with a header record, and possibly a little junk. In addition to tolerating lack of this column we should read in the topics table prior to opening the writer to address that
