### ISSUE TITLE
mcap cli 0.0.18 `failed to read messages` 

### ISSUE THREAD

**Issue by chenrui333** [foxglove/mcap#580]
**Description**

Trying to install the latest mcap cli 0.0.18, but failed to run `mcap cat`

- Version: mcap CLI0.0.18
- Platform: macOS
- go version: 1.19.1

**Steps To Reproduce**

- `go install github.com/foxglove/mcap/go/cli/mcap@latest`
- `cat OneMessage-ch-chx-mx-pad-rch-rsh-st-sum.mcap | xxx/golang/1.19.1/packages/bin/mcap cat`

**Expected Behavior**

`2 example [Example] [1 2 3]`

**Actual Behavior**

`2022/09/14 17:25:51 Failed to read messages: end cannot come before start`

---

relates to https://github.com/Homebrew/homebrew-core/pull/110694

**Comment by wkalt** [comment]
@chenrui333 thanks - fixed in v0.0.19.
