### ISSUE TITLE
Typescript mcap library requires lodash but does not depend on it

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/mcap#588]
https://github.com/foxglove/mcap/blob/main/typescript/core/src/v0/ChunkCursor.ts#L2

Installing @mcap/core and trying to use the v0 library results in errors because `lodash` is not listed as a dependency. I should be able to install `@mcap/core` as a dependency without having to install additional dependencies manually.

**Comment by jtbandes** [comment]
Another: https://github.com/foxglove/mcap/blob/dd261694e3232c513f3777204e513f7c529d90d4/typescript/core/src/v0/Mcap0StreamReader.ts#L2
