### ISSUE TITLE
Homebrew version of mcap records a strange library string

### ISSUE THREAD

**Issue by jhurliman** [foxglove/mcap#591]
**Description**

After installing mcap with Homebrew, running `mcap filter` on a file followed by `mcap info` on the resulting file shows the following library string:

```
library: mcap go #(devel); mcap go #(devel)
```

The same string is repeated twice with a `;` separator, and the version is reported as "devel" even though this is the official 0.0.19 release distributed via Homebrew.

- Version: 0.0.19
- Platform: MacOS (M1)

**Comment by jtbandes** [comment]
FWIW, homebrew manually passes `VERSION=v...` when building: https://github.com/Homebrew/homebrew-core/blob/d313c0378c0392bf14848879943d24dcfafb4325/Formula/mcap.rb#L32

Not sure how this would end up being `#(devel)`.

**Comment by jtbandes** [comment]
https://github.com/foxglove/mcap/blob/d96232ffd8d88c0e041ff6bb1dbba7eef87d1b44/go/mcap/writer.go#L55

**Comment by jtbandes** [comment]
It looks like the version is pulled from here with `git describe --tags`:

https://github.com/foxglove/mcap/blob/2079142e0e86f0926564adb86d6d95d3f40b057a/go/cli/mcap/Makefile#L23

This could be using the version number from some homebrew repo and not the mcap repo.

**Comment by jtbandes** [comment]
I'm still seeing that `mcap go #(devel);` gets prepended to whatever the library string was before `mcap filter`.

**Comment by james-rms** [comment]
`(devel)` comes from here: https://github.com/golang/go/issues/29228
