### ISSUE TITLE
Add "generic-protobuf" profile

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/mcap#62]
Should we have a `generic-protobuf` profile which clarifies how to store protobuf data in an mcap file.

**Comment by jtbandes** [comment]
Why "generic-"?

**Comment by defunctzombie** [comment]
Dunno. Somehow seemed easier to distinguish from frameworks that might use protobuf as well. I'd be 👍 on just `protobuf3` or whatever is appropriate. Guess wanted to make it obvious someone could define a different profile that uses protobuf encoding but maybe that is obvious enough.

**Comment by jhurliman** [comment]
I thought you just set profile to `""` to accomplish this.
