### ISSUE TITLE
Chunk records should have a start and end stamp

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/mcap#63]
With a start and end stamp on chunks, I could cheaply identify if I need to read a chunk or decompress a chunk based on the time I want to read messages at. Without the start and end stamp I have to process a chunk before knowing it contains messages for my timestamp.

**Comment by wkalt** [comment]
+1

**Comment by defunctzombie** [comment]
Captured in the branch here: https://github.com/foxglove/mcap/tree/roman/spec-format/docs/specification
