### ISSUE TITLE
Publish decompression handler boilerplate to NPM

### ISSUE THREAD

**Issue by jtbandes** [foxglove/mcap#719]
Some boilerplate is required to set up decompression handlers when reading an MCAP file. In https://github.com/foxglove/ws-protocol/pull/270 I copy/pasted some of the code we use for this from another repo. We have similar code both here and in foxglove/studio. These should be published to NPM so they can be reused.

Library name ideas:
- `@mcap/compression-support`
- `@mcap/wasm-compression-support`

**Comment by jhurliman** [comment]
There is also boilerplate needed to define readers for node.js and web file handles. Could those be rolled into the same package?

**Comment by jtbandes** [comment]
Depends how granular/hygienic you want the dependencies to be. Would a web user import the same package as a nodejs user?

**Comment by jhurliman** [comment]
I was thinking something like https://github.com/foxglove/ros2/blob/main/nodejs.js
