### ISSUE TITLE
rust: no way to limit chunk size automatically

### ISSUE THREAD

**Issue by james-rms** [foxglove/mcap#727]
**Description**

Right now if you write an MCAP with the rust client, you will end up with one large chunk full of all of your messages unless you explicitly call `finish_chunk`. This can result in giant chunks that are larger than `2**31` bytes. This can cause errors in readers which assume that a chunk can be held in memory all at once.

- Version: `releases/rust/v0.5.0`
- Platform: All

**Steps To Reproduce**

**Expected Behavior**

**Actual Behavior**

**Comment by neilisaac** [comment]
@james-rms finish_chunk is currently private, and chunks are buffered in memory, so this is a critical issue.

**Comment by james-rms** [comment]
@neilisaac for now you can call `flush()` which is public and should do what you need.
