### ISSUE TITLE
specification: metadata records must appear outside chunks

### ISSUE THREAD

**Issue by wkalt** [foxglove/mcap#732]
We have a disclaimer to this effect about attachments. The same needs to apply for metadata records, if the record is to be referenced by metadata index records. A metadata record that appears within a chunk cannot be referenced by a metadata index record today, which relies on a global file offset - compression will mess with a reader's ability to actually make use of an offset into compressed data.

There is potentially some leeway if there is a reason to permit recording unindexed metadata records into chunks. To keep things simple, seems best to me that the spec ban this.

**Comment by jtbandes** [comment]
> A Chunk contains a batch of Schema, Channel, and Message records.

https://github.com/foxglove/mcap/tree/main/docs/specification#chunk-op0x06

**Comment by james-rms** [comment]
@wkalt do you still think the metadata record needs this disclaimer?
