### ISSUE TITLE
Extend the "ros2" profile with well-known Channel metadata for storing QoS profiles

### ISSUE THREAD

**Issue by jhurliman** [foxglove/mcap#741]
The [mcap rosbag2 storage plugin](https://github.com/ros-tooling/rosbag2_storage_mcap/) is missing a feature that the default sqlite storage plugin has: storing QoS profile information in the recording. Since this is per-channel information, Channel metadata seems like the most straightforward place to put it. This would involve extending the `"ros2"` well-known profile documented in this repo with key names and a description of the values. The key names used in rosbag2's `metadata.yml` can be found at https://github.com/ros2/rosbag2/blob/master/rosbag2_transport/src/rosbag2_transport/qos.cpp#L70-L78

**Comment by james-rms** [comment]
The `offered_qos_profile` key in channel metadata is already mandated in the ROS2 appendix to the spec, and the mcap storage plugin already implements this by encoding the full QoS profile metadata as YAML and storing it under that key. I think it might be worth clarifying the spec appendix to say how the QoS profile metadata should be encoded (as yaml).
