### ISSUE TITLE
mcap convert cannot parse bounded string fields

### ISSUE THREAD

**Issue by james-rms** [foxglove/mcap#765]
**Description**

- Version: latest
- Platform: any

**Steps To Reproduce**

ROS2 can set bounds on some message types, ie:
https://github.com/ros2/test_interface_files/blob/9735cbc1b4116c3f59289e2be45b1bd70a3b4e40/msg/Strings.msg#L9
```
string<=22 bounded_string_value_default1 "Hello world!"
```

currently the `.msg` parser in the MCAP CLI doesn't know how to handle this.

**Expected Behavior**

**Actual Behavior**

**Comment by defunctzombie** [comment]
Fixed in https://github.com/foxglove/mcap/issues/765
