### ISSUE TITLE
Ambiguous wording in the MCAP File Format Specification

### ISSUE THREAD

**Issue by sanjaynarayanan-brt** [foxglove/mcap#792]
The following wording in the specification of a Chunk is a bit ambiguous -

> All messages in the chunk must reference channels recorded earlier in the file (in a previous chunk or earlier in the current chunk).

It may be interpreted as "all channels must be in a chunk (previous or current)". However, as far as I'm aware, this is not necessary. Channels can be logged standalone outside a chunk, in the Data section. Please correct me if I'm wrong.

**Comment by james-rms** [comment]
Thanks for the report @sanjaynarayanan-brt  - the specification currently allows channel, schema, or message records both in chunks and directly in the data section within the same MCAP. however, most MCAP reader implementations won't handle this correctly. I will amend the spec to disallow this case.

**Comment by sanjaynarayanan-brt** [comment]
@james-rms Thanks! 

I'm not sure what MCAP reader runs under the hood in Foxglove Studio (specifically for plots), but we write channels and schemas directly into the data section and put messages into chunks, and that seems to work great with plots.
