### ISSUE TITLE
negative end time reported by `mcap info`, disagrees with duration

### ISSUE THREAD

**Issue by jhurliman** [foxglove/mcap#822]
**Description**

Repro file: [zfp.mcap.zip](https://github.com/foxglove/mcap/files/10773480/zfp.mcap.zip)

```
$ mcap info zfp.mcap
library: libmcap 1.0.0
profile: 
messages: 300
duration: 2562047h47m16.854775807s
start: 0.000
end: -0.090
compression:
        zstd: [1/1 chunks] [221.93 KiB/3.77 KiB (98.30%)] [0.00 B/sec] 
channels:
        (1) image              100 msgs (0.00 Hz)   : foxglove.CompressedImage [protobuf]    
        (2) camera_info        100 msgs (0.00 Hz)   : foxglove.CameraCalibration [protobuf]  
        (3) image_annotations  100 msgs (0.00 Hz)   : foxglove.ImageAnnotations [protobuf]   
attachments: 0
metadata: 0
```

**Comment by jtbandes** [comment]
According to the TS reader, the end time is in 2554:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/14237/220432137-0acc84fc-6095-463e-889d-81abf4540c04.png">

**Comment by jtbandes** [comment]
<img width="453" alt="image" src="https://user-images.githubusercontent.com/14237/220432383-fe9790c2-abb2-4b90-b859-22e7c26d3dd0.png">

**Comment by jhurliman** [comment]
0xfffffffffaa3b800 comes after 0x0!

**Comment by james-rms** [comment]
Yeah - figured the same thing, but i also figure we should be able to handle this.
