### ISSUE TITLE
statistics.message_count is not correct in mcap-py

### ISSUE THREAD

**Issue by HyokaChen** [foxglove/mcap#845]
**Description**
use the mcap-py to extract mcap's info, the statistics.message_count is not correct, below is in python:
<img width="659" alt="image" src="https://user-images.githubusercontent.com/13757028/223314695-2a8973ef-3395-4a05-9c88-d7e3393ef0c4.png">

below is mcap cli's result:
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/13757028/223314895-953e35d1-ccf9-49af-936c-122c5ddf9850.png">

- Version: mcap-py 1.0.1
- Platform: MacOS 13.2.1 Ventura

**Steps To Reproduce**

any mcap package with many topics

**Expected Behavior**
statistics.message_count = 30210

**Comment by jtbandes** [comment]
Thank you for the bug report. Would you be interested in creating a pull request to fix the issue?

**Comment by james-rms** [comment]
Hi @HyokaChen , are you able to provide the code you used to produce that python output? I don't see any code in the MCAP library itself that would produce a `compression.compression_ratio` value.

**Comment by jtbandes** [comment]
It looks like the bug stems from this line of code:

https://github.com/foxglove/mcap/blob/39545dbea9b40fbc55a58df8f4ceecd06150ce49/python/mcap/mcap/records.py#L482

**Comment by HyokaChen** [comment]
> It looks like the bug stems from this line of code:
> 
> https://github.com/foxglove/mcap/blob/39545dbea9b40fbc55a58df8f4ceecd06150ce49/python/mcap/mcap/records.py#L482

👍 the loop to extract the Chanel’s message_count override the initial value.

**Comment by HyokaChen** [comment]
> Hi @HyokaChen , are you able to provide the code you used to produce that python output? I don't see any code in the MCAP library itself that would produce a `compression.compression_ratio` value.

Hi，I write this python code refer to mcap’s cli code.😁😁
