### ISSUE TITLE
Message.sequence: wording mistake?

### ISSUE THREAD

**Issue by omegacoleman** [foxglove/mcap#926]
**Description**

Hi, I'm trying to implement a mcap-compatible bag facility for a self-driving system. While I appreciate your hard work, I suspect a wording mistake in `spec/index.md`:

```markdown
### Message (op=0x05)

...

| 4     | sequence     | uint32    | Optional message counter assigned by publisher. If not assigned by publisher, must be recorded by the recorder. |
```

It says the sequence is optional, but "If **not** assigned by publisher, must be recorded by the recorder.", wouldn't that contradict with 'optional'?

It seems like a wording mistake of "If assigned by publisher, must be recorded by the recorder."

**Comment by omegacoleman** [comment]
I proposed a fix in #927

**Comment by jtbandes** [comment]
Hi, I believe this is not really a wording mistake per se... it's trying to say that since the field is required, if the publisher does not provide a sequence number then the recorder will have to come up with one. However, I agree that the wording is unclear. We will discuss internally.

**Comment by omegacoleman** [comment]
> Hi, I believe this is not really a wording mistake per se... it's trying to say that since the field is required, if the publisher does not provide a sequence number then the recorder will have to come up with one.

Thanks for clarifying that out, this is important to me.

> However, I agree that the wording is unclear. We will discuss internally.

I'll leave this open for a while, since that would still contradict with the `Optional` part.

My suggestions would be:
- if the recorder `MUST` come up with a sequence, then the field is not optional, it's mandatory
- Add the `the recorder will have to come up with one` part to the specs to let everybody know

**Comment by wkalt** [comment]
@omegacoleman I have raised a PR here to propose some new wording if you're interested: https://github.com/foxglove/mcap/pull/938
