### ISSUE TITLE
"Latest" tag in releases no longer points to latest mcap-cli release

### ISSUE THREAD

**Issue by dedwardsVolley** [foxglove/mcap#944]
In the past this URL

https://github.com/foxglove/mcap/releases/latest/download/mcap-linux-amd64

would download the latest mcap-cli, but now it points to https://github.com/foxglove/mcap/releases/download/releases/rust/v0.7.1/mcap-linux-amd64 (404)

Was this intentional? Was "rust" mistakenly tagged?

**Comment by defunctzombie** [comment]
This is intentional: https://github.com/orgs/foxglove/discussions/796
