### ISSUE TITLE
How to convert mcap file to rosbag?

### ISSUE THREAD

**Issue by poodarchu** [foxglove/mcap#945]
**Description**
I want to convert a nuscenes mcap file to rosbag, how to do this?

- Version:
- Platform:

**Steps To Reproduce**

**Expected Behavior**

**Comment by defunctzombie** [comment]
@poodarchu This is a question and not a bug. Please be mindful of what label you use when opening an issue. Questions are better routed to the discussion board here: https://github.com/orgs/foxglove/discussions or our community slack.
